spring:
  datasource:
    url: jdbc:postgresql://db-account:5432/account_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/master.yaml

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

customer:
  service:
    url: http://customer-service/api/customers

server:
  port: 8081

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        record-exceptions:
          - java.lang.IllegalStateException