spring:
  datasource:
    url: jdbc:postgresql://db-customer:5432/customer_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/master.yaml

  application:
    name: customer-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/


